### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by OliverHuang1220** [TheShadow29/zsgnet-pytorch#11]
Hi@TheShadow29,
How long does the paper use a single GPU for training on Flickr30K and Referit? I only have one Nvidia gpu:)

**Comment by TheShadow29** [comment]
@OliverHuang1220 Its been some time but if I recall correctly, it was around 1 hour / epoch for Flickr30k using 300 x 300 image size on one 1080ti. For 600 x 600 it was roughly 50 mins / epoch using 4 gpus (1080 Ti).

For referit, it was faster, around 15-25 mins / epoch using 300 x 300 image size on a 1080Ti. 

Some of the runtimes would depend on your cpu specifications as well. 

Let me know if you get similar run times.

**Comment by OliverHuang1220** [comment]
Thank you for your quick reply. I'll let you know as soon as I get the results：)
