### ISSUE TITLE
the table 4 in paper.

### ISSUE THREAD

**Issue by Nimo1989** [TheShadow29/zsgnet-pytorch#12]
Thank you for your great work. Recently, I am interested in the zero-shot setting for referring expression comprehension task and have read your paper ” Zero-Shot Grounding of Objects from Natural Language Queries". 
I need do comparison experiment with your work, so I have a question about Table 4. The result is report on validation dataset or test dataset? I guest it for test dataset, right? 

Thanks very much and looking forward to hearing from you.

**Comment by TheShadow29** [comment]
@Nimo1989 Yes, table 4 is on test set. Ablation table (table 6) is on val set.
