### ISSUE TITLE
location of results.json file

### ISSUE THREAD

**Issue by chinmay5** [TheShadow29/zsgnet-pytorch#5]
In the data preparation script, I was not able to find the `results.json` file and the pipeline is not working because of that. I am not sure where exactly is the file present

**Comment by TheShadow29** [comment]
@chinmay5 Seems like I missed to add that one. I uploaded it to my drive: https://drive.google.com/file/d/1bERw4jx60CMeyAHgBC82aPqJ9NcAYIJV/view?usp=sharing

Note that, you don't need to data preparation, you can directly use the annotation provided in `DATA_README.md`. The data preparation is only if you want to recreate more splits.
