### ISSUE TITLE
reproducing model on referit

### ISSUE THREAD

**Issue by chuckgu** [TheShadow29/zsgnet-pytorch#7]
hi, thank you for sharing codes .

I tried to reproduce a results on referit dataset, but i was not able to reach out within 40 epochs.

Acc was around 0.35 which was 0.2 lower than number in the paper.

I did not change any setting, so can you suggest any tips for reproducing?

My setting and logs are below.

ds_to_use: refclef
emb_dim: 300
epochs: 30
gamma: 2
lamb_reg: 1
load_normally: True
load_opt: False
local_rank: 0
lr: 0.0001
lstm_dim: 128
matching_threshold: 0.6
mdl_to_use: retina
num_gpus: 2
nw: 8
nwv: 8
only_test: False
only_val: False
opt_fn: Adam
opt_fn_params:
  betas: [0.9, 0.99]
patience: 2
ratios: [1/2, 1, 2]
reduce_factor: 0.1
resize_img: [300, 300]
resume: True
resume_path:
scale_factor: 4
scales: [1, 2**(1/3), 2**(2/3)]
strict_load: True
tmp_path: ./tmp
use_bidirectional: True
use_focal: True
use_img: True
use_lang: True
use_multi: True
use_reduce_lr_plateau: True
use_same_atb: True
use_softmax: False
epochs    trn_loss  val_loss  trn_cls_ls  val_cls_ls  trn_box_ls  val_box_ls  trn_Acc   val_Acc   trn_MaxPos  val_MaxPos
11        0.6314    0.9759    0.6114      0.9393      0.0200      0.0366      0.4075    0.2945    0.9837      0.9692
12        0.5944    0.9765    0.5754      0.9421      0.0190      0.0345      0.4055    0.3128    0.9870      0.9684
13        0.5516    1.0506    0.5346      1.0120      0.0170      0.0387      0.4320    0.3136    0.9852      0.9610
14        0.5375    1.0342    0.5219      0.9972      0.0156      0.0371      0.4426    0.3063    0.9912      0.9653
15        0.3912    1.1772    0.3806      1.1373      0.0106      0.0399      0.5214    0.3515    0.9933      0.9601
16        0.3637    1.2997    0.3542      1.2566      0.0095      0.0431      0.5294    0.3480    0.9902      0.9522
17        0.3511    1.3821    0.3423      1.3358      0.0087      0.0463      0.5294    0.3515    0.9934      0.9463
18        0.3356    1.4874    0.3275      1.4390      0.0081      0.0484      0.5321    0.3502    0.9945      0.9409
19        0.3356    1.4966    0.3280      1.4483      0.0076      0.0484      0.5373    0.3507    0.9921      0.9398
20        0.3191    1.5148    0.3114      1.4659      0.0077      0.0489      0.5424    0.3529    0.9939      0.9395

**Comment by chuckgu** [comment]
FYI, after above experiment, I ran another training on single GPU with 16 batch.
I got a similar result as shown in the paper.

**Comment by TheShadow29** [comment]
Hi @chuckgu 

For some reasons, I didn't get notified by your above issue. 

Apologies for the delayed reply. It's great that it is solved, so I am closing the issue.

Feel free to re-open the issue in case of any queries. 

Thanks.
